name: flutter_application_1
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-120.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  shared_preferences: ^2.0.13
  dio: ^4.0.6
  http: ^0.13.4
  cached_network_image: ^3.2.1
  string_similarity: ^2.0.0
  dotted_border: ^2.0.0+2
  flutter_launcher_icons: ^0.9.3
  shimmer: ^2.0.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/lunchicon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/onBoarding/
    - assets/images/auth/
    - assets/images/icons/

    

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
